export const dashboardMockData = [
  {
    id: 1,
    userId: "MU07801",
    name: "John",
    phone: "0198276548",
    email: "johnvenic89@gmail.com",
    status: "New Account",
    date: ["12.02.2025", "20.04.2025"],
  },
  {
    id: 2,
    userId: "MU07802",
    name: "Alice",
    phone: "0173456721",
    email: "alice.johnson@email.com",
    status: "Existing Account",
    date: ["10.01.2025", "18.03.2025"],
  },
  {
    id: 3,
    userId: "MU07803",
    name: "Michael",
    phone: "0189023456",
    email: "michael.smith@email.com",
    status: "New Account",
    date: ["15.02.2025", "22.04.2025"],
  },
  {
    id: 4,
    userId: "MU07804",
    name: "Sophia",
    phone: "0169876543",
    email: "sophia.lee@email.com",
    status: "Existing Account",
    date: ["05.01.2025", "12.03.2025"],
  },
  {
    id: 5,
    userId: "MU07805",
    name: "David",
    phone: "0191122334",
    email: "david.brown@email.com",
    status: "New Account",
    date: ["11.02.2025", "25.04.2025"],
  },
  {
    id: 6,
    userId: "MU07806",
    name: "Emma",
    phone: "0176654321",
    email: "emma.wilson@email.com",
    status: "Existing Account",
    date: ["03.01.2025", "10.03.2025"],
  },
  {
    id: 7,
    userId: "MU07807",
    name: "Daniel",
    phone: "0184433221",
    email: "daniel.clark@email.com",
    status: "New Account",
    date: ["09.02.2025", "21.04.2025"],
  },
  {
    id: 8,
    userId: "MU07808",
    name: "Olivia",
    phone: "0195566778",
    email: "olivia.hall@email.com",
    status: "Existing Account",
    date: ["22.01.2025", "30.03.2025"],
  },
  {
    id: 9,
    userId: "MU07809",
    name: "James",
    phone: "0179988776",
    email: "james.walker@email.com",
    status: "New Account",
    date: ["14.02.2025", "28.04.2025"],
  },
  {
    id: 10,
    userId: "MU07810",
    name: "Charlotte",
    phone: "0187766554",
    email: "charlotte.king@email.com",
    status: "Existing Account",
    date: ["08.01.2025", "19.03.2025"],
  },
];

export const productCatalogueMockData = [
  {
    id: 1,
    productName: "Floral Silk Saree",
    collection: "Spring Collection",
    pattern: "Floral",
    fabricType: "Silk",
    stockQty: 120,
    article: "AR1001",
    color: "Red",
  },
  {
    id: 2,
    productName: "Classic Cotton Kurta",
    collection: "Summer Wear",
    pattern: "Plain",
    fabricType: "Cotton",
    stockQty: 40,
    article: "AR1002",
    color: "Blue",
  },
  {
    id: 3,
    productName: "Designer Lehenga",
    collection: "Wedding Special",
    pattern: "Embroidered",
    fabricType: "Georgette",
    stockQty: 15,
    article: "AR1003",
    color: "Maroon",
  },
  {
    id: 4,
    productName: "Casual Linen Shirt",
    collection: "Urban Style",
    pattern: "Striped",
    fabricType: "Linen",
    stockQty: 70,
    article: "AR1004",
    color: "White",
  },
  {
    id: 5,
    productName: "Printed Maxi Dress",
    collection: "Resort Wear",
    pattern: "Printed",
    fabricType: "Chiffon",
    stockQty: 55,
    article: "AR1005",
    color: "Yellow",
  },
];

export const ordersMockData = [
  {
    orderId: "ORD-1001",
    customerName: "John Doe",
    orderDate: "2026-03-10",
    orderStatus: "Pending",
    shippingStatus: "Processing",
  },
  {
    orderId: "ORD-1002",
    customerName: "Jane Smith",
    orderDate: "2026-03-09",
    orderStatus: "Completed",
    shippingStatus: "Shipped",
  },
  {
    orderId: "ORD-1003",
    customerName: "Michael Johnson",
    orderDate: "2026-03-08",
    orderStatus: "Cancelled",
    shippingStatus: "Not Shipped",
  },
  {
    orderId: "ORD-1004",
    customerName: "Emily Davis",
    orderDate: "2026-03-07",
    orderStatus: "Pending",
    shippingStatus: "Processing",
  },
  {
    orderId: "ORD-1005",
    customerName: "William Brown",
    orderDate: "2026-03-06",
    orderStatus: "Completed",
    shippingStatus: "Shipped",
  },
  {
    orderId: "ORD-1006",
    customerName: "Olivia Wilson",
    orderDate: "2026-03-05",
    orderStatus: "Pending",
    shippingStatus: "Processing",
  },
];

export const productCategory = [
  {
    label: "Curtain",
    value: "Curtain",
  },
  {
    label: "Rugs",
    value: "Rugs",
  },
  {
    label: "Furniture",
    value: "Furniture",
  },
    {
    label: "Cushions",
    value: "Cushions",
  },
   {
    label: "Uphoistory",
    value: "Uphoistory",
  },
];
